before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox

script:
  - swipl -g main ./utils/iniatialize_database -k root -s localhost
