# Build and run tests every night on non-Docker systems.
name: Native Build (ubuntu, macos)

on:
  schedule:
    - cron:  '45 1 * * *'
  workflow_dispatch:

jobs:

  build-and-test:

    strategy:
      # Run all jobs even when some jobs fail.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            swipl_release: stable
          - os: ubuntu-latest
            swipl_release: devel
          - os: macos-latest
            swipl_release: homebrew

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: ./.github/install-swi-prolog.sh ${{ matrix.swipl_release }}

      - name: Check out tus
        uses: actions/checkout@v3
        with:
          repository: terminusdb/tus
          path: tus
          ref: v0.0.5

      - name: Install tus
        run: swipl -g "pack_install('file://$GITHUB_WORKSPACE/tus', [interactive(false)])"

      - name: Install Protobuf Compiler (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Protobuf Compiler (macOS)
        if: runner.os == 'macOS'
        run: brew install protobuf

      - run: make

      - run: make test
